### ISSUE TITLE
Question: depth-channel format

### ISSUE THREAD

**Issue by k-a-z-u** [xqms/xtion#13]
I was just wondering what the 11 bits denote before and after the LUT is applied to them and how they can be converted to real distance measurements. Or does the LUT already convert them to a real world scale? Maybe we could add some inline documentation or write a few hints to the project's wiki page. Of courese I am willing to help :)

Yesterday I noticed that, after the LUT is applied, also values above (the advertised) 11 bits are possible and 12/13 bits are used for long distances. Is this due to the LUT and is this valid behaviour when the devices advertises it's pixel-format as "Y11 " ?

Have a nice sunday :)

**Comment by xqms** [comment]
We get 11 bits from the hardware, but convert it to millimeters. So Y11 was actually incorrect since we do the conversion in the driver.

The driver advertises 16 bit grayscale as of 264032c58458c2c5d54fcf5533b466139e9fa61e, so everything should be fine now.
