### ISSUE TITLE
Camera is not available after system startup, needs manual replugging.

### ISSUE THREAD

**Issue by sebastianhein** [xqms/xtion#15]
Hi,

thank you for your great implementation. I was looking for a way to avoid OpenNI and this kernel module looks very promising so far.
However, I cannot get the camera working on system startup. The IR Light is off, /dev/video* (or /dev/xtion-* ) is not there. Once I pull out the plug and put it back in, everything works perfectly fine.

I am working on Ubuntu 14.04 LTS. 
- reloading the kernelmodules did not work
- powercycling/reinitializing the usb ports did not work either

"lsusb" is showing the device, btw. 

I have two cameras, running two different firmwares: "5.8.22" and "the older one"

dmesg output:
<pre>
[   13.514365] xtion 1-4:1.0: xtion_probe: failed to claim interface  1 (-16)!
[   13.514425] xtion: probe of 1-4:1.0 failed with error -16
[   13.514439] usbcore: registered new interface driver xtion
</pre>

Any help will be highly appreciated.

Cheers,
Sebastian

**Comment by xqms** [comment]
Hi Sebastian,

thanks for your report. One issue might be that the USB sound driver (snd_usb_audio) is loaded before xtion and claims the interface. Could you provide a full dmesg log of your boot and/or try to prevent snd_usb_audio from loading (e.g. move the module somewhere else or blacklist it)?

**Comment by sebastianhein** [comment]
Woah! 
Thank you for the super fast reply. 
I blacklisted the _snd_usb_audio_ module and now it works like a charme! 

steps: created a file _/etc/modprobe.d/blacklist-snd_usb_audio.conf_
<pre>
# blacklisted audio because it conflicts with xtion driver
blacklist snd_usb_audio
</pre>

Thanks you, and have a beautiful day :-)
Sebastian

**Comment by xqms** [comment]
Thanks, I'll add a hint in in the README file. The proper way would be to prioritize xtion over snd_usb_audio somehow, but I'm not sure how this can be done.
Anyway, I'm glad that this fixes your issue ;-)
