### ISSUE TITLE
can't open 320x240 depth stream

### ISSUE THREAD

**Issue by sebastianhein** [xqms/xtion#16]
Hi,

first of all, thank you for that great work. A real lifesaver, (almost) literally.
I am currently working with 640x480 depth streams but due to bandwidth limitations I want to switch to 320x240. Looking at the sources it should be supported, however, I can't make it work.
I am using python via the v4l2capture package.

Short code snippet:
`video = v4l2capture.Video_device('/dev/video1')`
`video.set_fps(30)`
`w, h = video.set_format(320, 240, 'Y16 ')`

Everything works fine for 640x480. Setting the parameters also looks fine, no errors in syslog. But once I start pulling images out of the device, I get flooded by "Missed packets: 17648 -> 17651" (with changing numbers)

Any ideas? 

Thanks,
Sebastian

**Comment by xqms** [comment]
just to confirm: Does the issue only occur with the depth stream? RGB at 320x240 works fine?
I'll take a look later this evening, when I have access to my xtion camera.

**Comment by xqms** [comment]
Could you test the current master? I was able to reproduce and fix the issue on my system. It seems one has to set one of the >80 hidden parameters to get 320x240 depth data...

**Comment by sebastianhein** [comment]
Thanks again!
Works perfectly fine now.

I could not really test the current master though, because i am bound to linux 3.16 on which the driver  does not compile after commit ab4bdfc6f2c13b0dc4dde5c647646173103f6d7d ("compile on 4.4.0")
Cherry Picking solved it for now.

I will create a fork.

**Comment by xqms** [comment]
Glad to hear that it works for you.

Yes, the kernel API changes all the time. That is the curse of out-of-tree drivers. xtion is not ready for submission to the kernel though and would probably be rejected.
So my current policy is to keep it compiling under the newest kernel versions. If you want to maintain a fork for older kernels I'd welcome it.

Anyway, thanks for reporting the issue ;-)
